"""Constants for the PiKVM integration."""
DOMAIN = "pikvm_ha"
CONF_HOST = "url"
CONF_USERNAME = "username"
CONF_PASSWORD = "password"
CONF_CERTIFICATE = "tls-certificate"
CONF_SERIAL = "serial"
DEFAULT_USERNAME = "admin"
DEFAULT_PASSWORD = "admin"
MANUFACTURER = "PiKVM"
