"""Constants for the PiKVM integration."""
DOMAIN = "pikvm_ha"
CONF_URL = "url"
CONF_USERNAME = "username"
CONF_PASSWORD = "password"
CONF_CERTIFICATE = "tls-certificate"
DHCP_CONFIG_FLAG="dhcp-config"
DEFAULT_USERNAME = "admin"
DEFAULT_PASSWORD = "admin"
DHCP_MAC_FILTER_PREFIXES = [ "e45f01", "dca632" ]
